# GitHub Pages Configuration
title: "Minecraft Modpack Analysis"
description: "Community mod suggestions vs final modpack comparison"
author: "Your Community Name"
email: "your-email@example.com"

# Theme
theme: minima

# GitHub Pages settings
baseurl: ""
url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"

# Navigation
header_pages:
  - README.md

# SEO
lang: en_US
twitter:
  username: your_twitter
  card: summary

# Analytics (optional)
google_analytics: # Your GA tracking ID

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - README.md
  - node_modules
  - vendor
  - .github
